name: Build & Deploy python package 

on:
  pull_request:
    branches:
      - 'main'
    paths: # only trigger docker builds when changes are made to src
      - 'src/pyveb/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: bump version
        run: poetry version patch
      - name: Commit bumped version
        uses: EndBug/add-and-commit@v9 
        with:
          add: '*.toml'
          author_name: Github CICD Action 
          committer_name: Github CICD Action 
          message: 'Bump version via Github Actions'
      - name: build with poetry
        run: poetry build
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Commit bumped version
        uses: EndBug/add-and-commit@v9 
        with:
          author_name: Github CICD Action 
          committer_name: Github CICD Action 
          fetch: false
          message: 'Bump version via Github Actions'
          pathspec_error_handling: ignore
